
package com.example.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IHelloWorld", targetNamespace = "http://service.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IHelloWorld {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHelloWorld", targetNamespace = "http://service.example.com/", className = "com.example.service.GetHelloWorld")
    @ResponseWrapper(localName = "getHelloWorldResponse", targetNamespace = "http://service.example.com/", className = "com.example.service.GetHelloWorldResponse")
    @Action(input = "http://service.example.com/IHelloWorld/getHelloWorldRequest", output = "http://service.example.com/IHelloWorld/getHelloWorldResponse")
    public String getHelloWorld(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
