
package com.isbank.opsvcs.collateralhandling.appraisalservice.service.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * Includes basic operations needed in the appraisal service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AppraisalServiceV1x5", targetNamespace = "http://isbank.com/OpSvcs/CollateralHandling/AppraisalService/Service/V1")
@XmlSeeAlso({
    com.isbank.opsvcs.collateralhandling.appraisalservice.service.v1.ObjectFactory.class,
    com.isbank.financialmgmt.treasury.schema.v1.ObjectFactory.class,
    com.isbank.technical.ea.fault.schema.v1.ObjectFactory.class,
    com.isbank.technical.ea.refdata.schema.v1.ObjectFactory.class
})
public interface AppraisalServiceV1X5 {


    /**
     * 
     * 				isIdempotent = YES -- TR:/Varolan ekspertiz firmalarý getirmek için {Ekspertiz firmalarý} -- EN:/To get the existing appraisal companies {Appraisal companies}
     * 			
     * 
     * @return
     *     returns com.isbank.opsvcs.collateralhandling.appraisalservice.service.v1.GetAppraisalCompaniesResponse.GetAppraisalCompaniesResponseDTO
     * @throws BusinessFault
     * @throws SystemFault
     */
    @WebMethod(action = "http://isbank.com/OpSvcs/CollateralHandling/AppraisalService/Service/V1/getAppraisalCompanies")
    @WebResult(name = "getAppraisalCompaniesResponseDTO", targetNamespace = "http://isbank.com/OpSvcs/CollateralHandling/AppraisalService/Service/V1")
    @RequestWrapper(localName = "getAppraisalCompanies", targetNamespace = "http://isbank.com/OpSvcs/CollateralHandling/AppraisalService/Service/V1", className = "com.isbank.opsvcs.collateralhandling.appraisalservice.service.v1.GetAppraisalCompanies")
    @ResponseWrapper(localName = "getAppraisalCompaniesResponse", targetNamespace = "http://isbank.com/OpSvcs/CollateralHandling/AppraisalService/Service/V1", className = "com.isbank.opsvcs.collateralhandling.appraisalservice.service.v1.GetAppraisalCompaniesResponse")
    public com.isbank.opsvcs.collateralhandling.appraisalservice.service.v1.GetAppraisalCompaniesResponse.GetAppraisalCompaniesResponseDTO getAppraisalCompanies()
        throws BusinessFault, SystemFault
    ;

    /**
     * 
     * 				isIdempotent = YES -- TR:/Varolan bir ekspertizin bilgilerini getirmek için {Ekspertizin bilgileri} -- EN:/To get the information of an existing appraisal under the given referance number {The information of an existing appraisal} 
     * 			
     * 
     * @param referenceNo
     * @return
     *     returns com.isbank.opsvcs.collateralhandling.appraisalservice.service.v1.GetAppraisalInfoByRefNoResponse.GetAppraisalInfoByRefNoResponseDTO
     * @throws BusinessFault
     * @throws SystemFault
     */
    @WebMethod(action = "http://isbank.com/OpSvcs/CollateralHandling/AppraisalService/Service/V1/getAppraisalInfoByRefNo")
    @WebResult(name = "getAppraisalInfoByRefNoResponseDTO", targetNamespace = "http://isbank.com/OpSvcs/CollateralHandling/AppraisalService/Service/V1")
    @RequestWrapper(localName = "getAppraisalInfoByRefNo", targetNamespace = "http://isbank.com/OpSvcs/CollateralHandling/AppraisalService/Service/V1", className = "com.isbank.opsvcs.collateralhandling.appraisalservice.service.v1.GetAppraisalInfoByRefNo")
    @ResponseWrapper(localName = "getAppraisalInfoByRefNoResponse", targetNamespace = "http://isbank.com/OpSvcs/CollateralHandling/AppraisalService/Service/V1", className = "com.isbank.opsvcs.collateralhandling.appraisalservice.service.v1.GetAppraisalInfoByRefNoResponse")
    public com.isbank.opsvcs.collateralhandling.appraisalservice.service.v1.GetAppraisalInfoByRefNoResponse.GetAppraisalInfoByRefNoResponseDTO getAppraisalInfoByRefNo(
        @WebParam(name = "referenceNo", targetNamespace = "http://isbank.com/OpSvcs/CollateralHandling/AppraisalService/Service/V1")
        String referenceNo)
        throws BusinessFault, SystemFault
    ;

}
