
package com.isbank.opsvcs.collateralhandling.appraisalservice.service.v1;

import javax.xml.ws.WebFault;
import com.isbank.technical.ea.fault.schema.v1.BusinessFaultType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "BusinessFault", targetNamespace = "http://isbank.com/OpSvcs/CollateralHandling/AppraisalService/Service/V1")
public class BusinessFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BusinessFaultType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public BusinessFault(String message, BusinessFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public BusinessFault(String message, BusinessFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.isbank.technical.ea.fault.schema.v1.BusinessFaultType
     */
    public BusinessFaultType getFaultInfo() {
        return faultInfo;
    }

}
